### PR TITLE
fix(checkbox): correct V2 spacing behavior

### LINKED ISSUE #3399: V2 checkbox spacing fix: remove auto-margin, add CheckboxList gap
Checkboxes in V2 have unwanted bottom margin from the auto-margin behavior (`mb ??= size === "compact" ? "s" : "m"`). This causes alignment issues when checkboxes are used in tables or other layouts where the parent should control spacing.

image

## Changes needed:
- Remove auto-margin from Checkbox in V2 mode
- Have CheckboxList control spacing via gap property instead
- Add GoabxCheckboxList experimental wrappers (React + Angular)

### PR DESCRIPTION
**Pull request by twjeffery**
## Summary
- Remove automatic margin-bottom from Checkbox in V2 mode
- Let CheckboxList control spacing via gap property
- Add playground test pages for visual verification

## Changes
- `Checkbox.svelte`: Removed auto-margin (`mb ??= size === "compact" ? "s" : "m"`)
- `CheckboxList.svelte`: Changed `gap: 0` to `gap: var(--goa-space-m)`
- `featV2Checkbox.tsx`: Test page at `/features/v2-checkbox`

### Before
image
image

### After
image

(^^ no unwanted bottom margin)

image

(^^ should look the same)

Added GoabxCheckboxList experimental wrappers for React and Angular — there wasn't one for checkbox-list yet, only for checkbox. Follows the Goabx pattern from #3357, auto-defaults version="2" and accepts a size prop.

## Testing
- [ ] Visit `/features/v2-checkbox` in React playground
- [ ] Verify checkboxes in a list have consistent spacing
- [ ] Verify standalone checkboxes no longer have unwanted bottom margin

## Related
- Spacing fix for V2 checkbox styling to match design specs

### CODE REVIEW

File: libs/react-components/src/lib/checkbox-list/checkbox-list.tsx [hunk 1]
```diff
@@ -21,6 +21,8 @@ interface WCProps extends Margins {
   error?: string;
   testid?: string;
   maxwidth?: string;
+  version?: string;
+  size?: string;
```
Comment (chrisolsen) [inline libs/react-components/src/lib/checkbox-list/checkbox-list.tsx]: Do these new props need to be here?

File: libs/react-components/src/lib/checkbox-list/checkbox-list.tsx
Comment (chrisolsen) [inline libs/react-components/src/lib/checkbox-list/checkbox-list.tsx]: This block of code should be moved to the experimental component

**Review by vanessatran-ddi — DISMISSED** [review]

**Review by vanessatran-ddi — APPROVED** [review]

**Review by chrisolsen — APPROVED** [review]
