### PR TITLE
fix(#3635): add in new color token for input leading icon

### LINKED ISSUE #3635: Input: Leading icon color
## Description

The leading icon in `GoabxInput` uses the default icon color, which is too dark. It should use a lighter color so it reads as secondary to the input text.

## Expected

- The leading icon should use `--goa-color-greyscale-600` (and/or a new component token is created: `--goa-text-input-colour-icon`) so it feels like a visual hint rather than competing with the input text.

## Screenshots
Current

Image

Design

Image

### PR DESCRIPTION
**Pull request by mxsoco**
# Before (the change)
The colour of the leading icon shared the same colour as the input text.

image

# After (the change)
With the new token added, the leading icon is lighter than the input text.

image

## Steps needed to test
- [ ] Confirm that v2 input, both default and compact sizes, are both using the  `--goa-text-input-colour-icon` design token.

### CODE REVIEW

**Review by bdfranck — COMMENTED** [review]
Almost there! I left a couple comments.

**Review by bdfranck — APPROVED** [review]
I looked at the latest changes...

The leading and trailing icons in a v2 input are `greyscale.600`. ✅  

Image

The leading and trailing icons in a v1 input (with v1 tokens) are the default colour. ✅ 

Image

Looks good to me! 👍

File: libs/web-components/src/components/input/Input.svelte [hunk 1]
```diff
@@ -651,6 +651,11 @@
     cursor: default !important;
   }
 
+  .leading-icon,
+  .trailing-icon {
+    color: var(--goa-text-input-color-icon);
+  }
+
   /* Adjust the leading icon style when input is disabled */
```
Comment (chrisolsen) [inline libs/web-components/src/components/input/Input.svelte]: Can this be moved up to line ~590 to keep it close the other matching selectors?

**Review by twjeffery — APPROVED** [review]
