### PR TITLE
fix(#3411): audit and improve all component configuration examples

### LINKED ISSUE #3411: Update the website configuration examples to include all relevant component variants
There are some component variants and properties that are not shown in any examples or config examples on the updated [design system website](https://goa-design-2.netlify.app/). 

Image

### List of known missing examples:
- [compact dropdown](https://goa-design-2.netlify.app/components/dropdown/#tab-1)
- 

As part if this work, do a quick review of all components to see if any other relevant variants are missing, and add them as applicable to the config examples.

### PR DESCRIPTION
**Pull request by twjeffery**
## Summary

- Audited all ~75 component configuration examples against Svelte source props
- Fixed critical bugs: spinner missing required size, data-grid using fabricated props, footer using wrong WC tags, drawer using wrong prop names, link using non-existent href, focus-trap using wrong prop
- Added missing variant configs across 30+ components (filter-chip icons, modal callout variants, data-grid keyboard nav, work-side-menu profiles, and more)
- Made file upload and table sorting configs interactive with scripts
- Fixed ConfigurationPreview version auto-injection for microsite-header
- Fixed framework consistency: WC attribute casing, Angular event bindings, correct component tags

## Test plan
- [ ] Review the config examples on the built site here: https://ds-config-examples-updates.netlify.app/components/#grid
- [ ] Browse each component page and verify config previews render correctly
- [ ] Test interactive configs: file upload (upload a file, see card appear), table sorting (click sort headers)
- [ ] Check all three framework tabs show consistent code

---
## Related issues
_Issues discovered during the config examples audit:_

**Created:**

- #3657 - Temporary notification: progress and indeterminate types not rendering correctly
- #3658 - Text: secondary color token is too dark
- #3659 - App header menu: dropdown popover has no border radius
- #3660 - File upload input: button should allow customization
- #3661 - Footer meta section: layout breaks at mid breakpoint
- #3662 - Menu button: closing the menu swallows the next click event
- #3663 - Pagination: page dropdown placeholder is truncated

**Added to existing:**

- #3649 - Callout: size prop has no visual effect (added comment)

---

## Needs team discussion

- Link button: Should `goa-link-button` stay on the docs site? If yes, it needs to be updated and fixed (variants, sizing, spacing to align with 2.0 buttons and links)
- Form: Should `goa-public-form` be hidden from the docs site? It's an internal component that teams don't use directly.
- Table sticky header: Do we still support `stickyheader` in V2?  Need to decide if we fix it or remove it from the docs.

### CODE REVIEW

File: docs/src/data/configurations/app-header.ts [hunk 1]
```diff
@@ -94,32 +94,47 @@ export const appHeaderConfigurations: ComponentConfigurations = {
...
+      id: "with-navigation",
+      name: "With navigation",
+      description: "Header with navigation, groups, and utilities",
       code: {
         react: `<GoabxAppHeader heading="Service Portal" url="/">
-  <a slot="navigation" href="/dashboard">Dashboard</a>
-  <a slot="navigation" href="/applications">Applications</a>
-  <a slot="navigation" href="/settings">Settings</a>
+  <a slot="navigation" href="#">Dashboard</a>
+  <GoabxAppHeaderMenu slot="navigation" heading="Applications" type="primary">
```
Comment (vanessatran-ddi) [inline docs/src/data/configurations/app-header.ts]: same vs `app-header-menu.ts`, code should use `slotName` , not `slot`

File: docs/src/data/configurations/button-group.ts [hunk 2]
```diff
@@ -4,124 +4,123 @@
...
   configurations: [
     {
-      id: 'basic',
-      name: 'Basic button group',
-      description: 'Group of buttons with default spacing',
+      id: "basic",
+      name: "Basic button group",
+      description: "Group of buttons with default spacing",
       code: {
         react: `<GoabButtonGroup>
```
Comment (vanessatran-ddi) [inline docs/src/data/configurations/button-group.ts]: `GoabButtonGroup` must have `alignment` defined.

File: docs/src/data/configurations/card-actions.ts [hunk 3]
```diff
@@ -4,18 +4,18 @@
  * CardActions is a child component of Card.
  */
 
-import type { ComponentConfigurations } from './types';
+import type { ComponentConfigurations } from "./types";
```
Comment (vanessatran-ddi) [inline docs/src/data/configurations/card-actions.ts]: Do we need this (DS website 1.0 doesn't have Card and its sub component page)
https://ds-config-examples-updates.netlify.app/components/card/#react#properties

**Review by vanessatran-ddi — COMMENTED** [review]
I just complete phase 1 review, tomorrow I will continue 😅

**Review by vanessatran-ddi — COMMENTED** [review]
I still continue, just move to IDE to review, browser loads so slow for me

File: docs/src/data/configurations/container.ts [hunk 4]
```diff
@@ -4,105 +4,247 @@
...
+</goa-container>`,
+      },
+    },
+    {
+      id: "with-heading",
+      name: "With heading",
+      description: "Container with title slot",
+      code: {
+        react: `<GoabContainer accent="thick" type="non-interactive">
+  <div slot="title">Application details</div>
```
Comment (vanessatran-ddi) [inline docs/src/data/configurations/container.ts]: For react wrapper, correct code snippet should be <GoabContainer .... title='Application details'>, not using 'slot'

File: docs/src/data/configurations/divider.ts [hunk 5]
```diff
@@ -4,44 +4,28 @@
...
-      name: 'With margins',
-      description: 'Divider with custom spacing',
-      code: {
-        react: `<p>Section one</p>
+        react: `<GoabText mt="none" mb="none">Section one</GoabText>
 <GoabDivider mt="xl" mb="xl" />
-<p>Section two</p>`,
-        angular: `<p>Section one</p>
+<GoabText mt="none" mb="none">Section two</GoabText>`,
+        angular: `<goa-text>Section one</goa-text>
```
Comment (vanessatran-ddi) [inline docs/src/data/configurations/divider.ts]: angular code here should use `<goab-text>` instead of `goa-text`

File: docs/src/data/configurations/footer-nav-section.ts [hunk 6]
```diff
@@ -4,18 +4,18 @@
...
+  defaultConfigurationId: "basic",
 
   configurations: [
     {
-      id: 'basic',
-      name: 'Basic footer nav section',
-      description: 'Navigation section within Footer',
+      id: "basic",
+      name: "Basic footer nav section",
+      description: "Navigation section within Footer",
```
Comment (vanessatran-ddi) [inline docs/src/data/configurations/footer-nav-section.ts]: angular code snippet line 27 should use `goabx-app-footer` and `goabx-app-footer-nav-section`

File: docs/src/data/configurations/footer-nav-section.ts [hunk 7]
```diff
@@ -31,13 +31,59 @@ export const footerNavSectionConfigurations: ComponentConfigurations = {
...
+    <a href="/housing">Housing</a>
+    <a href="/transportation">Transportation</a>
+    <a href="/environment">Environment</a>
+    <a href="/business">Business</a>
+    <a href="/taxes">Taxes and finance</a>
+    <a href="/legal">Legal services</a>
+  </GoabxAppFooterNavSection>
+</GoabxAppFooter>`,
+        angular: `<goab-footer>
+  <goab-footer-nav-section heading="All services" [maxColumnCount]="3">
```
Comment (vanessatran-ddi) [inline docs/src/data/configurations/footer-nav-section.ts]: same vs here, angular code snippet should use the new components for `goabx-app-footer`, `goabx-app-footer-meta-section`, `goabx-app-footer-nav-section`

File: docs/src/data/configurations/hero-banner.ts [hunk 8]
```diff
@@ -4,28 +4,46 @@
...
+        react: `<GoabHeroBanner heading="Start your application">
+  <p>Apply for government services quickly and easily online.</p>
+  <GoabButtonGroup mt="l">
+    <GoabxButton>Get started</GoabxButton>
+    <GoabxButton type="secondary">Learn more</GoabxButton>
+  </GoabButtonGroup>
+</GoabHeroBanner>`,
+        angular: `<goab-hero-banner heading="Start your application">
+  <p>Apply for government services quickly and easily online.</p>
+  <goab-button-group mt="l">
```
Comment (vanessatran-ddi) [inline docs/src/data/configurations/hero-banner.ts]: same vs angular, we are missing `alignment` property for `goab-button-group`

File: docs/src/data/configurations/popover.ts [hunk 9]
```diff
@@ -4,123 +4,123 @@
...
+      description: "Simple popover with content",
       code: {
         react: `<GoabPopover>
-  <GoabxButton slot="target">Open popover</GoabxButton>
-  <p>Popover content goes here. It can contain any content.</p>
+  <GoabxButton slotName="target">Open popover</GoabxButton>
+  <GoabText mt="none" mb="none">Popover content goes here. It can contain any content.</GoabText>
 </GoabPopover>`,
         angular: `<goab-popover>
   <goabx-button slot="target">Open popover</goabx-button>
```
Comment (vanessatran-ddi) [inline docs/src/data/configurations/popover.ts]: same vs angular code snippet too

File: docs/src/data/configurations/tabs.ts [hunk 10]
```diff
@@ -75,43 +97,85 @@ export const tabsConfigurations: ComponentConfigurations = {
...
+      name: "With badge in heading",
+      description: "Tab heading with a badge using the heading slot",
       code: {
-        react: `<GoabxTabs variant="segmented">
-  <GoabTab heading="Day">Daily view</GoabTab>
-  <GoabTab heading="Week">Weekly view</GoabTab>
-  <GoabTab heading="Month">Monthly view</GoabTab>
+        react: `<GoabxTabs>
+  <GoabTab heading="Messages">
+    <goa-text>Your messages will appear here.</goa-text>
```
Comment (vanessatran-ddi) [inline docs/src/data/configurations/tabs.ts]: We should use `GoabText`

**Review by vanessatran-ddi — COMMENTED** [review]
I finally finish my review. Good work @twjeffery

File: docs/src/data/configurations/scrollable.ts [hunk 11]
```diff
@@ -2,65 +2,69 @@
  * Scrollable Component Configurations
```
[the remark this answers is not in the document]
Comment (vanessatran-ddi) [reply docs/src/data/configurations/scrollable.ts]: I see eslint error: type {webComponents: string;} is missing the following properties from type: react, angular. I think to simplifer this fix, at line 22 and line 36, you can add back `react: ""` and `angular: ""`

File: docs/src/data/configurations/container.ts [hunk 12]
```diff
@@ -4,105 +4,247 @@
...
+  <p>Container content with a heading using the title slot.</p>
+</goab-container>`,
+        webComponents: `<goa-container accent="thick" type="non-interactive">
+  <div slot="title">Application details</div>
+  <p>Container content with a heading using the title slot.</p>
+</goa-container>`,
+      },
+    },
+    {
+      id: "with-heading-and-actions",
```
[the remark this answers is not in the document]
Comment (vanessatran-ddi) [reply docs/src/data/configurations/container.ts]: Missing this comment.

File: docs/src/data/configurations/focus-trap.ts [hunk 13]
```diff
@@ -4,20 +4,20 @@
...
     {
-      id: 'basic',
-      name: 'Basic focus trap',
-      description: 'Container that traps keyboard focus',
+      id: "basic",
+      name: "Basic focus trap",
+      description: "Container that traps keyboard focus",
       code: {
-        react: `<GoabFocusTrap active={isActive}>
+        react: `<GoabFocusTrap open={isActive}>
```
[the remark this answers is not in the document]
Comment (vanessatran-ddi) [reply docs/src/data/configurations/focus-trap.ts]: I think we should delete this file. FocusTrap is for internal use only.

**Review by vanessatran-ddi — APPROVED** [review]
I have only some small comments but I do not think it is a blocker, so I approve.

File: docs/src/data/configurations/focus-trap.ts [hunk 14]
```diff
@@ -2,40 +2,23 @@
...
-  <goabx-form-item label="Username" mb="l">
-    <goabx-input name="username" width="100%"></goabx-input>
-  </goabx-form-item>
-  <goabx-form-item label="Password" mb="l">
-    <goabx-input name="password" type="password" width="100%"></goabx-input>
-  </goabx-form-item>
-  <goabx-button>Submit</goabx-button>
-</goab-focus-trap>`,
-        webComponents: `<goa-focus-trap active>
+        webComponents: `<goa-focus-trap open>
```
Comment (vanessatran-ddi) [inline docs/src/data/configurations/focus-trap.ts]: We can remove this file like card-action.ts. This component is for internal use only

File: docs/src/data/configurations/app-header.ts
Comment (ArakTaiRoth) [inline docs/src/data/configurations/app-header.ts]: Here, and other locations, you're using a slot property on GoabButton. This property doesn't exist, neither does slotName.

File: docs/src/data/configurations/app-header-menu.ts [hunk 15]
```diff
@@ -4,35 +4,35 @@
...
-      id: 'basic',
-      name: 'Basic app header menu',
-      description: 'Navigation menu within AppHeader',
+      id: "basic",
+      name: "Basic app header menu",
+      description: "Navigation menu within AppHeader",
       code: {
         react: `<GoabAppHeader heading="My Application">
-  <GoabAppHeaderMenu slot="nav">
+  <GoabAppHeaderMenu slotName="navigation">
```
Comment (ArakTaiRoth) [inline docs/src/data/configurations/app-header-menu.ts]: You're missing the required `heading` property

File: docs/src/data/configurations/modal.ts [hunk 16]
```diff
@@ -59,68 +59,176 @@ export const modalConfigurations: ComponentConfigurations = {
...
+</goa-modal>
+<script>${modalScript}</script>`,
+      },
+    },
+    {
+      id: "callout-information",
+      name: "Information callout",
+      description: "Modal with information callout header",
+      code: {
+        react: `<GoabModal heading="New features available" open={isOpen} closable calloutVariant="information" onClose={handleClose}>
```
Comment (ArakTaiRoth) [inline docs/src/data/configurations/modal.ts]: Same here

File: docs/src/data/configurations/modal.ts [hunk 17]
```diff
@@ -59,68 +59,176 @@ export const modalConfigurations: ComponentConfigurations = {
...
+</goa-modal>
+<script>${modalScript}</script>`,
+      },
+    },
+    {
+      id: "callout-success",
+      name: "Success callout",
+      description: "Modal with success callout header",
+      code: {
+        react: `<GoabModal heading="Application submitted" open={isOpen} closable calloutVariant="success" onClose={handleClose}>
```
Comment (ArakTaiRoth) [inline docs/src/data/configurations/modal.ts]: Same here

File: docs/src/data/configurations/modal.ts [hunk 18]
```diff
@@ -59,68 +59,176 @@ export const modalConfigurations: ComponentConfigurations = {
...
+</goa-modal>
+<script>${modalScript}</script>`,
+      },
+    },
+    {
+      id: "callout-event",
+      name: "Event callout",
+      description: "Modal with event callout header",
+      code: {
+        react: `<GoabModal heading="Scheduled maintenance" open={isOpen} closable calloutVariant="event" onClose={handleClose}>
```
Comment (ArakTaiRoth) [inline docs/src/data/configurations/modal.ts]: Same here

File: docs/src/data/configurations/modal.ts [hunk 19]
```diff
@@ -59,68 +59,176 @@ export const modalConfigurations: ComponentConfigurations = {
...
 </goa-modal>
+<script>${modalScript}</script>`,
+      },
+    },
+    {
+      id: "custom-width",
+      name: "Custom width",
+      description: "Modal with specified maximum width",
+      code: {
+        react: `<GoabModal heading="Wide modal" open={isOpen} maxWidth="80ch" closable onClose={handleClose}>
```
Comment (ArakTaiRoth) [inline docs/src/data/configurations/modal.ts]: Same here

**Review by vanessatran-ddi — APPROVED** [review]
Looks good!

File: docs/src/data/configurations/form.ts [hunk 20]
```diff
@@ -4,18 +4,18 @@
  * Form wraps form elements with proper structure.
  */
```
Comment (ArakTaiRoth) [inline docs/src/data/configurations/form.ts]: Every example here is also using `onSubmit`, if this is for `GoabFormItem`, that doesn't have an `onSubmit` property. If this is for `GoabPublicForm`, that also doesn't have `onSubmit`, it has `onInit`, `onComplete`, and `onStateChange`.

File: docs/src/data/configurations/footer.ts [hunk 21]
```diff
@@ -4,28 +4,56 @@
...
     {
-      id: 'basic',
-      name: 'Basic footer',
-      description: 'Simple page footer',
+      id: "basic",
+      name: "Basic footer",
+      description: "Simple page footer",
       code: {
         react: `<GoabAppFooter />`,
         angular: `<goab-footer></goab-footer>`,
```
Comment (ArakTaiRoth) [inline docs/src/data/configurations/footer.ts]: All angular examples throughout this file are wrong. None of them have `-app-` in the name.

File: docs/src/data/configurations/link-button.ts [hunk 22]
```diff
@@ -4,44 +4,28 @@
  * LinkButton provides button-styled anchor elements.
```
[the remark this answers is not in the document]
Comment (twjeffery) [reply docs/src/data/configurations/link-button.ts]: Agreed, I deleted the config file. We can revisit if/when the component gets proper wrapper support.

File: docs/src/data/configurations/form.ts (hunk 20 above)
Comment (twjeffery) [reply docs/src/data/configurations/form.ts]: Deleted this config file for now and we can add it in later if we decide to

File: docs/src/data/configurations/form.ts [hunk 23]
```diff
@@ -4,18 +4,18 @@
  * Form wraps form elements with proper structure.
```
[the remark this answers is not in the document]
Comment (twjeffery) [reply docs/src/data/configurations/form.ts]: deleted

File: docs/src/data/configurations/app-header.ts
Comment (twjeffery) [reply docs/src/data/configurations/app-header.ts]: Leaving as-is for now. Sounds like this is a wrapper-level issue. Might be worth discussing with Chris whether slot should be added to the wrapper interfaces.

Comment (ArakTaiRoth) [reply docs/src/data/configurations/app-header.ts]: @chrisolsen Input?

**Comment by twjeffery** [comment]
@ArakTaiRoth  Fixed the missing `version="2"` on the parent `goa-app-header` in app-header-menu.ts. 

Also rebased onto latest dev to fix the build issues

File: docs/src/data/configurations/app-header.ts
Comment (chrisolsen) [reply docs/src/data/configurations/app-header.ts]: In React all the props passed in are output to the web-component. So `slot` will be set on the `goa-badge` element.

**Review by ArakTaiRoth — APPROVED** [review]
