### PR TITLE
fix(#3493): show tooltip on hover for Work Side Menu Group

### LINKED ISSUE #3493: Work side menu group doesn't show tooltip on hover when collapsed
When the WorkSideMenu is collapsed, hovering over a WorkSideMenuGroup does not display a tooltip with the group label. Individual WorkSideMenuItem components show tooltips correctly when collapsed, but groups do not.

### Steps to Reproduce
1. Render a WorkSideMenu with collapsed={true}
2. Include a WorkSideMenuGroup with a label
3. Hover over the collapsed group icon
4. Expected: Tooltip appears showing the group label
5. Actual: No tooltip appears

https://github.com/user-attachments/assets/fc8f850b-7afa-4860-be05-17d6ee527a2a

### Expected Behavior 
When the side menu is collapsed, hovering over a WorkSideMenuGroup should show a tooltip with the group's label, matching the behavior of WorkSideMenuItem.

### PR DESCRIPTION
**Pull request by bdfranck**
# Before (the change)

I cannot see a tooltip when I hover a Work Side Menu Group in a closed menu.

https://github.com/user-attachments/assets/3c2cea1a-70a4-4ff4-9f1c-6a4bb128238c

# After (the change)

https://github.com/user-attachments/assets/872abfc4-b2e0-40c0-ac6a-d60180df3d3a

I can see a tooltip when I hover a Work Side Menu Group in a closed menu.

## Make sure that you've checked the boxes below before you submit the PR

- [ ] I have read and followed the [setup steps](https://goa-dio.atlassian.net/wiki/spaces/DS/pages/3086385489/Contribution+-+web+content#%5BinlineExtension%5DCode-contributions)
- [ ] I have created necessary unit tests
- [ ] I have tested the functionality in both React and Angular.

## Steps needed to test
1. Close the Work Side Menu
2. Hover the icon of a Work Side Menu Group

### CODE REVIEW

File: libs/web-components/src/components/work-side-menu/WorkSideMenuGroup.svelte [hunk 1]
```diff
@@ -2,20 +2,26 @@
 
 <script lang="ts">
   import type { GoAIconType } from "../icon/Icon.svelte";
-  import { toBoolean } from "../../common/utils";
+  import { toBoolean, dispatch } from "../../common/utils";
```
Comment (vanessatran-ddi) [inline libs/web-components/src/components/work-side-menu/WorkSideMenuGroup.svelte]: I think we should have a unit test - create a new file WorkSideMenuGroup.spec.ts, to cover the case:
when `mouseenter` or `hover` on the `details` element, the `_hoverItem` event will be dispatched if browser test is difficult to be written.

Image

**Review by vanessatran-ddi — COMMENTED** [review]
It is good, I tested on my local. I just have 1 comment.

**Review by willcodeforcoffee — APPROVED** [review]
LGTM 👍

File: libs/web-components/src/components/work-side-menu/WorkSideMenuGroup.spec.ts [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+
+    const fn = vi.fn();
+    container.addEventListener("_hoverItem", fn);
+
+    const details = container.querySelector("details");
+    expect(details).toBeTruthy();
+
+    await fireEvent.mouseEnter(details!);
+
+    expect(fn).toHaveBeenCalled();
```
Comment (vanessatran-ddi) [inline libs/web-components/src/components/work-side-menu/WorkSideMenuGroup.spec.ts]: Can we verify:
```
 expect(fn).toHaveBeenCalled();
  const event = fn.mock.calls[0][0];
  expect(event.detail.label).toBe("Test Group");
  expect(event.detail.el).toBeTruthy();
```
Just to make sure the tooltip is triggered vs the correct heading.

**Review by vanessatran-ddi — APPROVED** [review]

**Comment by bdfranck** [comment]
@vanessatran-ddi Thanks for the review! I've updated the test with your suggestion.

**Review by chrisolsen — APPROVED** [review]
